if [ "${INCLUDE_SYNTH_SH+is_defined}" ]; then
	return
fi
INCLUDE_SYNTH_SH=true

NOTE_PITCH_CSV=src/note_pitch.csv

OSC_PCM_AREA_BASE=25A01000
OSC_PCM_NUM_SAMPLES=A8
OSC_PCM_NUM_SAMPLES_DEC=$(echo "ibase=16;$OSC_PCM_NUM_SAMPLES" | bc)
OSC_PCM_TXT_FILE_SAW=src/pcm_c4_saw_16bit.txt
OSC_PCM_SAW_MC68K_BASE=00001000
OSC_PCM_SQU_HIGH=7fff
OSC_PCM_SQU_LOW=8000
OSC_PCM_SQU_MC68K_BASE=00001150
OSC_PCM_TXT_FILE_SIN=src/pcm_c4_sin_16bit.txt
OSC_PCM_SIN_MC68K_BASE=000012A0
SLOT_NOT_FOUND=7f
SYNTH_MIDIMSG_QUEUE_BASE=25A70000

OSC_CURSOR_X=2c
OSC_CURSOR_Y_SAW=60
OSC_CURSOR_Y_SQU=86
OSC_CURSOR_Y_SIN=ad

PROGNUM_OSC_SAW=01
PROGNUM_OSC_SQU=02
PROGNUM_OSC_SIN=03
PROGNUM_OSC_NOISE=04
PROGNUM_LFO_PLFOWS_SSAW=05
PROGNUM_LFO_PLFOWS_SQU=06
PROGNUM_LFO_PLFOWS_DSAW=07
PROGNUM_LFO_PLFOWS_NOISE=08
PROGNUM_LFO_ALFOWS_SSAW=09
PROGNUM_LFO_ALFOWS_SQU=0a
PROGNUM_LFO_ALFOWS_DSAW=0b
PROGNUM_LFO_ALFOWS_NOISE=0c

DUMP_EG_AR_X=40
DUMP_EG_AR_Y=77
DUMP_EG_D1R_X=83
DUMP_EG_D1R_Y=70
DUMP_EG_D2R_X=a6
DUMP_EG_D2R_Y=8d
DUMP_EG_RR_X=ee
DUMP_EG_RR_Y=9e
DUMP_EG_DL_X=10
DUMP_EG_DL_Y=98
DUMP_LFO_LFOF_X=10
DUMP_LFO_LFOF_Y=10
DUMP_LFO_PLFOS_X=40
DUMP_LFO_PLFOS_Y=10
DUMP_LFO_ALFOS_X=70
DUMP_LFO_ALFOS_Y=10
